### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by rb08081** [edqx/amongus-protocol#1]
(node:5000) ExperimentalWarning: The ESM module loader is experimental.
file:///C:/Users/......./Desktop/AmongUS/node_modules/amongus-protocol/js/lib/Client.js:420
            if (options.doSpawn ?? true) {
                                 ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)

**Comment by dada513** [comment]
what's you version of nodejs?

**Comment by edqx** [comment]
Should be fixed with 2b0e84c77b7ad4491582cc06ca0c578580813150
