### ISSUE TITLE
Running test script throws Join error: 0 - (Forcibly disconnected from server.)

### ISSUE THREAD

**Issue by MateusAquino** [edqx/amongus-protocol#11]
Not quite sure what's happening but running the default test script in my environment is throwing `Join error: 0` every single time, steps I used:

## Installing
**Input**

    git clone https://github.com/edqx/amongus-protocol

**Output**

>     Cloning into 'amongus-protocol'...
>     remote: Enumerating objects: 59, done.
>     remote: Counting objects: 100% (59/59), done.
>     remote: Compressing objects: 100% (43/43), done.
>     remote: Total 2791 (delta 33), reused 32 (delta 16), pack-reused 2732
>     Receiving objects: 100% (2791/2791), 865.37 KiB | 1.33 MiB/s, done.
>     Resolving deltas: 100% (2451/2451), done.

**Input**

    cd amongus-protocol
    npm i

**Output**

>     > amongus-protocol@1.1.31 postinstall C:\Users\mateu\Documents\GitHub\aptest\amongus-protocol
>     > npm run build
>     
>     
>     > amongus-protocol@1.1.31 build C:\Users\mateu\Documents\GitHub\aptest\amongus-protocol
>     > tsc -p .
>     
>     npm notice created a lockfile as package-lock.json. You should commit this file.
>     npm WARN typedoc-plugin-nojekyll@1.0.1 requires a peer of typedoc@^0.11.1 but none is installed. You must install peer dependencies yourself.
>     
>     added 52 packages from 396 contributors and audited 52 packages in 33.621s
>     
>     3 packages are looking for funding
>       run `npm fund` for details
>     
>     found 0 vulnerabilities

## Running

**Input**

    npm run test

**Output**

>     > amongus-protocol@1.1.31 test C:\Users\mateu\Documents\GitHub\aptest\amongus-protocol
>     > npm run load ts/test/main.ts
>     
>     
>     > amongus-protocol@1.1.31 load C:\Users\mateu\Documents\GitHub\aptest\amongus-protocol
>     > node --loader ts-node/esm "ts/test/main.ts"
>     
>     (node:17576) ExperimentalWarning: The ESM module loader is experimental.
>     (node:17576) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
>     (node:17576) UnhandledPromiseRejectionWarning: Error: Join error: 0 (Forcibly disconnected from server. The remote sent a disconnect request.)
>         at AmongusClient.<anonymous> (file:///C:/Users/mateu/Documents/GitHub/aptest/amongus-protocol/ts/lib/Client.ts:602:23)
>         at Generator.next (<anonymous>)
>         at fulfilled (file:///C:/Users/mateu/Documents/GitHub/aptest/amongus-protocol/ts/lib/Client.ts:4:58)
>         at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     (node:17576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
>     (node:17576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Env
OS: Windows 10
Node: v12.18.4
TS: 4.0.5 (same as package.json)
ts-node: 9.0.0 (same as package.json)

**Comment by edqx** [comment]
You need to provide a game code in the test as the first argument.
e.g. `npm run test CDISMN`
I also suggest using Node >14, I've had others have issues with node 12. I need to update the README.

Also worth noting that the join consistently gives `0` as an error code for some reason, even if it's a different reason, and I've been unable to fix it however many times I've tried.

**Comment by MateusAquino** [comment]
Oh yeah, it worked passing an EU code using Node v14.15.0, Thank you!
