### ISSUE TITLE
clientver in the Hello packet should be parsed as int32BE instead of int32LE

### ISSUE THREAD

**Issue by jdf221** [edqx/amongus-protocol#14]
Not 100% positive on this because honestly I don't fully understand that stuff.

But I was having an issue with the game reporting that I was running an older version of the game and changing the Parser to read the `clientver` as big endian seemed to fix it.

For context I am using the parser and composer to read/modify the packets being sent from the real game to the server, so I was parsing the Hello packet and then composing it and then sending it to the server. Which resulted in the old game error, even though I wasn't modifying the packet at all.

Specifically the line I'm talking about:

https://github.com/edqx/amongus-protocol/blob/master/ts/lib/Parser.ts#L476

and here it is in the compose function being wrote as big endian:

https://github.com/edqx/amongus-protocol/blob/master/ts/lib/Compose.ts#L428

**Comment by edqx** [comment]
Interesting, looks like it should be Little Endian. https://github.com/codyphobe/among-us-protocol/blob/master/01_packet_structure/05_packet_types.md#0x08-hello
Thanks for bringing this up, I'll commit some changes to fix this now.
