### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Warhawk001** [edqx/amongus-protocol#15]
So I am trying to use this package but I have come across a couple of errors and I can not seem to solve them so I am looking for help. So I figured out the first to which were to specify es5 in the tsc command as well as to specify --downlevelIteration but I am still left with this error `node_modules/amongus-protocol/ts/lib/util/BufferWriter.ts:1:8 - error TS1192: Module '"util"' has no default export.` and others similar to it. I would appreciate any help or answer once again thank you for the help I am kind of new to typescript so ya.

**Comment by edqx** [comment]
If you haven't already, youlu should update node to v14+ and typescriot to v4+.

**Comment by Warhawk001** [comment]
Thank you for the response. Yes I am currently running node version 14.15.1 and typescript version 4.1.2 but I still seem to get there error when compiling the ts file.

**Comment by edqx** [comment]
What command are you running?

If you're using your own command, I suggest using `--allowSyntheticDefaultImports`.

**Comment by Warhawk001** [comment]
OMG thank you so much it seems like the ts file compiled with no errors but now when I go to run the index.js file generated I get this error. `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:`. Do you known if there is anyways for me to avoid this errors in the feature with out having to pass in the arguments to the tsc command since I already have them in the tsc config.

**Comment by edqx** [comment]
I think you need to add `"type": "module"` to the nearest `package.json` and it should be fine.

I'm not sure what you mean by
> Do you known if there is anyways for me to avoid this errors in the feature with out having to pass in the arguments to the tsc command since I already have them in the tsc config.
If you want to pass `--allowSyntheticDefaultImports` you can just add `"allowSyntheticDefaultImports": true` to the `tsconfig.json`.
