### ISSUE TITLE
Proper Tut?

### ISSUE THREAD

**Issue by chibbi** [edqx/amongus-protocol#26]
I wanted to use it, but it didn't work. i never use TypeScript, so maybe it is because of that, but when i try to compile it, or install with npm it gives out errors and does't work.

**Comment by edqx** [comment]
There's not really much assistance I want to provide without ending up spoon-feeding, there are examples provided and the installation is fairly straight forward.

If you're having issues installing, you need to tell me what these issues are instead of just saying that it's not working.
