### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DOGGOLOVER679** [edqx/amongus-protocol#28]
Error: Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher.

Code: import {
    AmongusClient,
    MasterServers,
    ColourID,
    HatID,
} from "./node_modules/amongus-protocol/js/index"
 
const server = MasterServers.EU[0];
 
const client = new AmongusClient({
    
});
 
await client.connect(server[0], server[1], "weakeyes");
 
const game = await client.join(process.argv[2]);
 
game.me.on("spawn", () => {
    game.me.setName("weakeyes");
    game.me.setColour(ColourID.Black);
    game.me.setHat(HatID.Plague);
});

(I copy pasted the code from the example)

I don't have any experience with typescript can anyone help me?

**Comment by edqx** [comment]
Add a `(async() => { /* code */ })()` wrapper around your entire code (except imports).

**Comment by DOGGOLOVER679** [comment]
Ty
