### ISSUE TITLE
voting in meetings crashes bot

### ISSUE THREAD

**Issue by dada513** [edqx/amongus-protocol#3]
My current code:
```js
game.on("startMeeting", () => {
    log("Meeting");
    setTimeout(() => {
      log("Voted");
      console.log(game.options.emergencyCooldown);
      game.me.vote(game.me);
    }, game.options.emergencyCooldown * 1500);
  });
```
The bot does not vote in the meeting, but leaves the game. Among us says that "user has left due to an error", but there are no errors in the console.

**Comment by dada513** [comment]
btw, thank you for creating this project! This is awesome

**Comment by edqx** [comment]
I will have a look at this. I haven't had the opportunity to test this properly.

**Comment by edqx** [comment]
Hi, I've pushed a fix with 83ec1f427ef22176906107664ecec6ce3bb8f54d that might help, sorry for the wait, was missing a few things before it could work.
![image](https://user-images.githubusercontent.com/60631511/97784473-c5a68100-1b96-11eb-8718-a08a2ef0f5f6.png)

**Comment by edqx** [comment]
There's an example in ts/tests/main.ts if needed.

**Comment by dada513** [comment]
Thank you!
