### ISSUE TITLE
ExpirementalWarning

### ISSUE THREAD

**Issue by DOGGOLOVER679** [edqx/amongus-protocol#30]
Error:
node:7619) ExperimentalWarning: The ESM module loader is experimental.
file:///home/....../amongus/index.js:38
exports.__esModule = true;
^

ReferenceError: exports is not defined
    at file:///home/...../amongus/index.js:38:1
    at ModuleJob.run (internal/modules/esm/module_job.js:146:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:84:5)

**Comment by edqx** [comment]
Hi, can I see how you're running the code? Like the command that you're using.
Thanks.

**Comment by DOGGOLOVER679** [comment]
node index.js

**Comment by edqx** [comment]
I think I told you to add `"type": "module"` to your package.json at #29, but you should remove that & use CommonJS imports rather than the es6 import syntax. Using the code you posted on the same issue, it would be ```js
const {
AmongusClient,
MasterServers,
ColourID,
HatID,
} = require("amongus-protocol");
```
Rather than what you had before at the top of the script.

**Comment by DOGGOLOVER679** [comment]
Ok
