### ISSUE TITLE
Add more versatile logging system

### ISSUE THREAD

**Issue by iamcsharper** [edqx/amongus-protocol#5]
short question:

Problem: `debug` option being set to `false `does not guarantee not seeing any messages in the console during run.

- [x] Solution: add a `debug` condition check in the ShipStatus component

detailed solution:

- [x] Actually having one debug option isn't enough to maintain debugging. It would be nice to have a `LogLevel enum` with bitmasks and a corresponding option to see raw data and/or decoded packets and/or emitted events and/or fired listeners, etc.

**Comment by edqx** [comment]
First is true, there is some manual debugging I have forgotten to remove in ShipStatus.

This is not a bad idea, I'll keep this in mind and likely add it when I get round to it.
