### ISSUE TITLE
Server: You are running an old version of the game

### ISSUE THREAD

**Issue by dada513** [edqx/amongus-protocol#7]
![image](https://user-images.githubusercontent.com/49000790/98523519-4ee44480-2276-11eb-973b-fda95009cbbb.png)
I keep getting this, even though I am running the latest one. Tried with among us stable and beta

**Comment by dada513** [comment]
Also, my code:
```js
import * as among from "amongus-protocol";
import nconf from "nconf";

nconf.argv().env().file({ file: "config.json" }).defaults({
  port: 22023,
});

const server = new among.AmongusServer({});

async function srv() {
  await server.listen(nconf.get("port"));
  console.log("Listening on", nconf.get("port"));
}
srv();
```

**Comment by edqx** [comment]
Hi the server is very much incomplete and you won't be able to use it for
now. I'm thinking about removing it as I'm working on a server as a side
project.
