### ISSUE TITLE
Mistike on Game Code Wikipage

### ISSUE THREAD

**Issue by knbedgm** [edqx/amongus-protocol#8]
On the wiki page for the Game Code it says:

> V1 codes are 4 characters long and V2 codes are 6 characters long and use standard ASCII encoding. V2 codes use a special character map to map the characters to integer values.

I believe it should actually say 

> V1 codes are 4 characters long and use standard ASCII encoding. V2 codes are 6 characters long and use a special character map to map the characters to integer values.

**Comment by edqx** [comment]
Yep I'll fix this now.
